import { atom } from 'jotai';
import build from 'next/dist/build';

const currentDate = new Date().toISOString().split('T')[0];

export const empFormData = atom({
  name: "",
  fatherName: "",
  designation: "",
  dob: "",
  currAddress: "",
  district: "",
  state: "",
  pincode: "",
  perAddress: "",
  perDistrict: "",
  perState: "",
  perPincode: "",
  companyName: "",
  companyAddress: "",
  department: "",
  bankName: "",
  accountNumber: "",
  ifsc: "",
  dateOfJoining: "",
  currstdcode: "",
  currcontactNumber: "",
  perstdcode: "",
  percontactNumber: "",
  companylocation: "",
  date: currentDate,
  eCode: '',
  pfNo: '',
  function: '',
  level: '',
  firstName: '',
  middleName: '',
  surname: '',
  familyMemberName: '',
  familyMemberOccupation: '',
  sex: '',
  bloodGroup: '',
  nationality: '',
  maritalStatus: '',
  spouseName: '',
  spouseDob: '',
  anniversaryDate: '',
  spouseBloodGroup: '',
  spouseEducation: '',
  spouseWorking: '',
  emergencyContactName: '',
  emergencyContactPhone: '',
  emergencyContactRelationship: '',
  gratuityNominee1Percent: '',
  gratuityNominee1Name: '',
  gratuityNominee2Percent: '',
  gratuityNominee2Name: '',
  pfNominee1Percent: '',
  pfNominee1Name: '',
  pfNominee2Percent: '',
  pfNominee2Name: '',
  pfNominee3Percent: '',
  pfNominee3Name: '',
  education: Array.from({ length: 1 }, () => Array(6).fill("")),
  employment: Array.from({ length: 1 }, () => Array(6).fill("")),
  games: "",
  ncc: "",
  hobbies: "",
  knowsSomeone: "",
  references: [
    { name: "", address: "", phone: "" },
    { name: "", address: "", phone: "" }
  ],
  convictionDetails: "",
  place: "",
  familyMembers: [{ name: "", relationship: "", dob: "", age: "" }],
  nominees: [{ name: "", relationship: "", dob: "", percentage: "" }],
  code: "",
  grade: "",
  members: [
    {
      name: "",
      relationship: "SELF",
      dob: "",
      age: "",
      amount: "",
    },
  ],
})

export const grauFormData = atom({
  name: "",
  noticedate: "",
  nominee: [
    {
      name: "",
      relationship: "",
      age: null,
      proportion: null,
    },
  ],
  sex: "",
  religion: "",
  marriagestatus: "",
  department: "",
  post: "",
  dateofappointment: "",
  building: "",
  village: "",
  thana: "",
  subdivision: "",
  postoffice: "",
  district: "",
  state: "",
  place: "",
  date: currentDate,
  witness1name: "",
  witness2name: "",
})
//write mongoose model for this data in ts

export const nominationForm1Data = atom({
  name: "",
  fathersName: "",
  dob: "",
  sex: "",
  maritalStatus: "",
  permanentAddress: "",
  currentAddress: "",
  nominees: [
    { name: "", address: "", relationship: "", dob: "", share: "", guardian: "" },
  ],
  place: "",
  date: currentDate,
  establishmentAddress: ""
})

export const nominationForm2Data = atom({
  name: '',
  firstName:'',
  middleName : '',
  surname: '',
  fatherName: '',
  dob: '',
  accountNumber: '',
  sex: '',
  maritalStatus: '',
  address: '',
  hasNoFamily: false,
  hasDependentParents: false,
  credit_nominees: [
    { name: '', address: '', relationship: '', dob: '', share: '', guardianName: '', guardianAddress: '' },
  ],
  familyMembers: [
    { name: '', address: '', age: '', relationship: '' },
  ],
  pension_nominee: {
    name: '',
    address: '',
    dob: '',
    relationship: ''
  },
  subscriberDate: currentDate,
  employerDate: currentDate,
  establishmentDetails: '',
  place: '',
  date: currentDate,
});

export const bankMandateFormData = atom({
  name: '',
  employeeCode: '',
  category: '',
  address: '',
  email: '',
  pan: '',
  bankName: '',
  branchPlace: '',
  branchCity: '',
  pincode: '',
  accountType: '',
  accountNumber: '',
  ifscCode: '',
  place: '',
  date: currentDate,
  categoryctdtstaff: '',
})

export const idCardFormData = atom({
  name: "",
  fatherName: "",
  designation: "",
  dob: "",
  currAddress: "",
  empcode: "",
  department: "",
  bloodGroup: "",
  dateOfJoining: "",
  contactnumber: "",
  photo: null as string | null,
  year: new Date().getFullYear().toString(),
})

export const staffFamilyFormData = atom({
  empNo: '',
  name: '',
  department: '',
  dob: '',
  age: 0,
  maritalStatus: '',
  spouseName: '',
  spouseDob: '',
  numOfChildren: '',
  children: [
    { name: '', gender: '', dob: '' },
    { name: '', gender: '', dob: '' }
  ],
  fatherName: '',
  fatherDob: '',
  motherName: '',
  motherDob: '',
  mobileNumber: '',
  address: '',
  date: currentDate
})

export const formStatusus = atom({
  token: "",
  forms : {
    form1: {
      name: "STAFF JOINING FORM",
      url: "/staff-joining",
      status: "pending",
    },
    form2: {
      name: "ID Card Form",
      url: "/idcard-form",
      status: "pending",
    },
    form3: {
      name: "Family Members Details",
      url: "/staff-family-members",
      status: "pending",
    },
    form4: {
      name: "Bank Mandate Form",
      url: "/bank-mandate",
      status: "pending",
    },
    form5: {
      name: "Form 1 Nomination & declaration",
      url: "/nomination-declaration-form1",
      status: "pending",
    },
    form6: {
      name: "Gratuity Form",
      url: "/gratuity-form",
      status: "pending",
    },
    form7: {
      name: "Form 2 Nomination & declaration",
      url: "/nomination-declaration-form2",
      status: "pending",
    },
  },
})