import type { Metadata } from "next";
import "./globals.css";
import { seedAdmin } from "@/lib/seedAdmin";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Employee Forms",
  description: "Generated by karan Jaiswal",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // await seedAdmin();
  return (
    <html lang="en" className="dark">
      <body className="bg-gray-200 dark:bg-neutral-950 text-gray-900 font-sans antialiased dark:text-gray-200">
        {children}
        <Toaster richColors closeButton />
      </body>
    </html>
  );
}
