// app/layout.tsx

import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import ThemeWrapper from "@/components/ThemeWrapper"; // You’ll create this

export const metadata: Metadata = {
  title: "Employee Forms",
  description: "Generated by Karan Jaiswal",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="bg-neutral-200 dark:bg-neutral-950 text-gray-900 font-sans antialiased dark:text-gray-200">
        <ThemeWrapper>
          {children}
          <Toaster richColors closeButton />
        </ThemeWrapper>
      </body>
    </html>
  );
}
